### PR TITLE
Add the talk by Farzad YZ

### PR DESCRIPTION
**Pull request by farskid**
TODO:
- [x] Add title and description of the talk
- [x] Update speaker info

### CODE REVIEW

**Comment by bebraw** [comment]
Thanks.

As it's a draft, I couldn't merge yet but I picked up the title already so I could generate the graphics: https://api.react-finland.fi/asset-designer?selectionId=TweetTemplate&themeId=react-finland&variables=%7B%22conferenceId%22%3A%22react-finland-2021%22%2C%22contactName%22%3A%22Farzad%20Yz%22%7D .

Ping me once it's ready to merge. 👍

**Comment by farskid** [comment]
I'll update my personal info and picture and un-draft it.

**Comment by farskid** [comment]
@bebraw This is good to go.

**Comment by bebraw** [comment]
Cool, thanks. 👍

**Pull request merged**
